title: Guilherme Brotto
email: guilhermebrotto.ml@gmail.com
description: >-
  Computer Science graduate from Federal University of Espírito Santo with experience in Software Development, Machine Learning, and Automation. Working with Python, C#, .NET, AWS, and PyTorch.

github_username: guilherme751
minimal_mistakes_skin: air
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone: America/Sao_Paulo
title_separator: "•"
repository: guilherme751/guilherme751.github.io

incremental: true
locale: en

social:
  name: Guilherme S. G. Brotto
  links:
    - https://github.com/guilherme751
    - https://www.linkedin.com/in/guilherme-s-g-brotto-13707b235

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Guilherme Brotto"
  avatar : "/assets/images/profile-pic.PNG"
  bio    : "Software Developer & ML Researcher. CS graduate from UFES."
  location: "Vitória, ES, Brazil"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:guilhermebrotto.ml@gmail.com"
    - label: "Curriculum"
      icon: "far fa-fw fa-file-pdf"
      url: "https://guilherme751.github.io/assets/documents/GuilhermeCurriculum.pdf"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guilherme-s-g-brotto-13707b235"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guilherme751"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guilherme751"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guilherme-s-g-brotto-13707b235"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
